name: Template Docker Build with Conan AMD64 + ARM64

env:
  namespace:  PLACEHOLDER             # TODO: REPLACE WITH: drone | bin | gcs ...
  conan:      PLACEHOLDER             # TODO: REPLACE WITH: true | false
  arch:       linux/amd64,linux/arm64 # TODO: replace with correct arch
  
on:
  push:
    branches: [ '*' ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  version:
    name: Handle version update
    runs-on: self-hosted
    container: jfrog.local:8081/reg/base/base-ci:master
    
    steps:
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0                # fetch the whole repo history
          persist-credentials: false
          
      - name: Handle version update
        uses: teveltech/github-tag-action@annotated-tag
        id: semantic
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true
          
      - name: Check new version
        run: |
          echo "Branch name: ${GITHUB_REF#refs/heads/}"
          echo "Pre-release: ${{ steps.semantic.outputs.prerelease }}"
          echo "Workflow was triggered from ${{ github.event_name }}"
          echo "Previous annotated tag: ${{ steps.semantic.outputs.previous_tag }}"
          echo "Previous lightweight tag: ${{ steps.semantic.outputs.previous_light_tag }}"
          if [ -z "${{ steps.semantic.outputs.new_tag }}" ]; then
            echo "::error::No version bump - no new tag or release will be created. Usually means the workflow was triggered manually or a new branch was created without any changes."
          else
            echo "New tag: ${{ steps.semantic.outputs.new_tag }}"
          fi
          
    outputs:
      new_tag: ${{ steps.semantic.outputs.new_tag }}
      new_version: ${{ steps.semantic.outputs.new_version }}
      changelog: ${{ steps.semantic.outputs.changelog }}
      previous_tag: ${{ steps.semantic.outputs.previous_tag }}
      prerelease: ${{ steps.semantic.outputs.prerelease }}
      previous_light_tag: ${{ steps.semantic.outputs.previous_light_tag }}
      
      
  Build:
    needs: version
    runs-on: self-hosted
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: ${{ secrets.JFROG_URL }}/reg/base/tonistiigi/binfmt:latest
          platforms: all
          
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Configure docker buildx
        uses: teveltech/buildx-action@master
          
      - name: Login to Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.JFROG_URL }}
          username: ${{ secrets.DOCKER_REGISTRY_USER }} 
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
          
      - name: Override version in conanpackage.py
        if: ${{ env.conan == 'true' }}
        uses: teveltech/version-action@master
        with:
          new_version: ${{ needs.version.outputs.new_tag }}
          
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ env.arch }}
          pull: true
          push: true
          tags: ${{ secrets.JFROG_URL }}/reg/${{ env.namespace }}/${{ github.event.repository.name }}:${{ needs.version.outputs.new_tag }}
          cache-from: type=registry,ref=${{ secrets.JFROG_URL }}/reg/${{ env.namespace }}/${{ github.event.repository.name }}:${{ needs.version.outputs.previous_light_tag }}
          cache-to: type=inline

  release:
    name: Git tag and GitHub release
    needs: [version, Build]
    runs-on: self-hosted
    container: jfrog.local:8081/reg/base/base-ci:master
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: git config
        run: |
          git config user.email "Tevel GitHub Runner"
          git config user.name "Tevel GitHub Runner"
          
      # note: adding a message would create an annotated tag
      - name: Create Lightweight Tag
        if: ${{ needs.version.outputs.new_tag && needs.version.outputs.prerelease == 'true' }}
        run: |
          git tag ${{ needs.version.outputs.new_tag }}
          git push --force origin ${{ needs.version.outputs.new_tag }}
          echo "New lightweight tag: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/tag/${{ needs.version.outputs.new_tag }}"
          
      - name: Create Annotated Tag
        if: ${{ needs.version.outputs.new_tag && needs.version.outputs.prerelease == 'false' }}
        run: |
          git tag -a ${{ needs.version.outputs.new_tag }} -m "${{ github.event.head_commit.message }}" 
          git push --force origin ${{ needs.version.outputs.new_tag }}
          echo "New annotated tag: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/tag/${{ needs.version.outputs.new_tag }}"
          
      - name: Create a GitHub release
        id: release
        if: ${{ needs.version.outputs.new_tag }}
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prerelease: ${{ needs.version.outputs.prerelease }}
          tag_name: ${{ needs.version.outputs.new_tag }}
          name: Release ${{ needs.version.outputs.new_tag }}
          body: |
            Docker pull command:
            <pre><code> docker pull jfrog.local:8081/reg/${{ env.namespace }}/${{ github.event.repository.name }}:${{ needs.version.outputs.new_tag }} </code></pre>
            
      - name: set warning
        shell: bash
        run: |
          STRING="New release: ${{ steps.release.outputs.url }}
          Docker pull command:
          docker pull jfrog.local:8081/reg/${{ env.namespace }}/${{ github.event.repository.name }}:${{ needs.version.outputs.new_tag }}"
          STRING="${STRING//'%'/'%25'}"
          STRING="${STRING//$'\n'/'%0A'}"
          STRING="${STRING//$'\r'/'%0D'}"
          echo "::warning::$STRING"
