name: Python Package Template

on:
  push:
    branches: [ '*' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  version:
    name: Handle version update
    runs-on: self-hosted
    container: jfrog.local:8081/reg/base/base-ci:master
    
    steps:
      - uses: teveltech/composite-version@master
        id: semantic
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Check new version
        shell: bash
        run: |
          echo "Branch name: ${{ steps.semantic.outputs.branch }}"
          echo "Pre-release: ${{ steps.semantic.outputs.prerelease }}"
          echo "Workflow was triggered from ${{ github.event_name }}"
          echo "Previous annotated tag: ${{ steps.semantic.outputs.previous-tag }}"
          echo "Previous lightweight tag: ${{ steps.semantic.outputs.previous-light-tag }}"
          if [ -z "${{ steps.semantic.outputs.new-tag }}" ]; then
            echo "::error::No version bump - no new tag or release will be created. Usually means the workflow was triggered manually or a new branch was created without any changes."
          else
            echo "New tag: ${{ steps.semantic.outputs.new-tag }}"
          fi
          
    outputs:
      new-tag: ${{ steps.semantic.outputs.new-tag }}
      new-version: ${{ steps.semantic.outputs.new-version }}
      changelog: ${{ steps.semantic.outputs.changelog }}
      previous-tag: ${{ steps.semantic.outputs.previous-tag }}
      prerelease: ${{ steps.semantic.outputs.prerelease }}
      previous-light-tag: ${{ steps.semantic.outputs.previous-light-tag }}
      branch: ${{ steps.semantic.outputs.branch }}
      
  python:
    needs: version
    name: Build & Push
    runs-on: self-hosted
    container: jfrog.local:8081/reg/base/base-core:master

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Build and push python package
        id: python
        uses: teveltech/composite-python@master
        with:
          new-tag: ${{ needs.version.outputs.new-tag }}
          
    outputs:
      package: ${{ steps.python.outputs.package }}
      
  release:
    name: Git tag and GitHub release
    needs: [version, python]
    runs-on: self-hosted
    container: jfrog.local:8081/reg/base/base-ci:master
    
    steps:     
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: true
          
      - name: Handle git tag and github release
        uses: teveltech/composite-release@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          new-tag: ${{ needs.version.outputs.new-tag }}
          prerelease: ${{ needs.version.outputs.prerelease }}
          changelog: ${{ needs.version.outputs.changelog }}
          body: |
            New python package:
            <pre><code> ${{ needs.python.outputs.package }} </code></pre>
          warning: |
            New python package:
            ${{ needs.python.outputs.package }}
            
