name: Python Package Template

# Controls when the action will run. 
on:
  push:
    branches: [ '*' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  version:
    # The type of runner that the job will run on
    runs-on: self-hosted
    container: jfrog.local:8081/reg/base/base-ci:master

    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0                # fetch the whole repo history
          persist-credentials: false

      - name: Handle version update
        uses: teveltech/github-tag-action@annotated-tag
        id: semantic
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true

      - name: Check new version
        run: |
          echo "Branch name: ${GITHUB_REF#refs/heads/}"
          echo "Pre-release: ${{ steps.semantic.outputs.prerelease }}"
          echo "Workflow was triggered from ${{ github.event_name }}"
          echo "Previous annotated tag: ${{ steps.semantic.outputs.previous_tag }}"
          echo "Previous lightweight tag: ${{ steps.semantic.outputs.previous_light_tag }}"
          if [ -z "${{ steps.semantic.outputs.new_tag }}" ]; then
            echo "::error::No version bump - no new tag or release will be created. Usually means the workflow was triggered manually or a new branch was created without any changes."
          else
            echo "New tag: ${{ steps.semantic.outputs.new_tag }}"
          fi

    outputs:
      new_tag: ${{ steps.semantic.outputs.new_tag }}
      new_version: ${{ steps.semantic.outputs.new_version }}
      changelog: ${{ steps.semantic.outputs.changelog }}
      previous_tag: ${{ steps.semantic.outputs.previous_tag }}
      prerelease: ${{ steps.semantic.outputs.prerelease }}
      previous_light_tag: ${{ steps.semantic.outputs.previous_light_tag }}

  Build:
    needs: version
    # The type of runner that the job will run on
    runs-on: self-hosted
    container: jfrog.local:8081/reg/base/base-full:master

    steps:

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Override version in setup.py
        uses: teveltech/version-action@master
        with:
          new_version: ${{ needs.version.outputs.new_tag }}
      
      - name: Link pypi config directory and .pypirc to github home /github/home
        run: ln -s /root/.pypirc $HOME/.pypirc && ln -s /root/.pip $HOME/.pip
      
      - name: Install dependencies needed to upload
        run: |
          pip2 install setuptools wheel twine
          pip3 install setuptools wheel twine
        
      - name: Install dependencies needed to build
        run: |
          if [ -f requirements.txt ]; then pip2 install -r requirements.txt; fi
          if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
          
      - name: Build and publish
        run: |
          python2 setup.py bdist_wheel upload -r local
          python3 setup.py bdist_wheel upload -r local

  release:
    name: Git tag and GitHub release
    needs: [version, Build]
    runs-on: self-hosted
    container: jfrog.local:8081/reg/base/base-ci:master

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      - name: git config
        run: |
          git config user.email "Tevel GitHub Runner"
          git config user.name "Tevel GitHub Runner"
          
      # note: adding a message would create an annotated tag
      - name: Create Lightweight Tag
        if: ${{ needs.version.outputs.new_tag && needs.version.outputs.prerelease == 'true' }}
        run: |
          git tag ${{ needs.version.outputs.new_tag }}
          git push --force origin ${{ needs.version.outputs.new_tag }}
          echo "New lightweight tag: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/tag/${{ needs.version.outputs.new_tag }}"
          
      - name: Create Annotated Tag
        if: ${{ needs.version.outputs.new_tag && needs.version.outputs.prerelease == 'false' }}
        run: |
          git tag -a ${{ needs.version.outputs.new_tag }} -m "${{ github.event.head_commit.message }}" 
          git push --force origin ${{ needs.version.outputs.new_tag }}
          echo "New annotated tag: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/tag/${{ needs.version.outputs.new_tag }}"

      - name: Create a GitHub release
        id: release
        if: ${{ needs.version.outputs.new_tag }}
        uses: softprops/action-gh-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prerelease: ${{ needs.version.outputs.prerelease }}
          tag_name: ${{ needs.version.outputs.new_tag }}
          name: Release ${{ needs.version.outputs.new_tag }}
          body: |
            ${{ needs.version.outputs.changelog }}

      - name: set warning
        shell: bash
        run: |
          STRING="New release: ${{ steps.release.outputs.url }}"
          STRING="${STRING//'%'/'%25'}"
          STRING="${STRING//$'\n'/'%0A'}"
          STRING="${STRING//$'\r'/'%0D'}"
          echo "::warning::$STRING"
